# https://jekyllrb.com/docs/configuration/options/

# Paginate
paginate: 10
paginate_path: /page:num

##### 一些本地测试开关, 其中livereload在上传时应设为false #####
livereload: true
open_url: true

timezone: Asia/Shanghai

include: [_pages]
permalink: "/:categories/:title:output_ext"

###### 自定义区域 Liquid配置 使用形如 site.xxx #####
title: INFINITY 中文如何呢

# Author settings
author: clearoce # add your name
author-pic: clearoce.jpg
about-author: A Ghost

# Contact links
email: clearoce315@gmail.com
website: www.clearoce.me # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: clearoce # Add your Github handle

plugins:
  - jekyll-avatar
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

